### ISSUE TITLE
Did you forget to add FID.py ?

### ISSUE THREAD

**Issue by UdonDa** [steffen-jung/SpectralGAN#1]
Hi @steffen-jung, Happy New Year!

Thank you for sharing your nice research!
I've read your paper and understood your motivation enough, which is to introduce an additional discriminator.

By the way, I think your implementation does not include 'FID.py' according to this line, 
>https://github.com/steffen-jung/SpectralGAN/blob/main/Training.py#L75

Please add this module!

Best regards

**Comment by steffen-jung** [comment]
Hi @UdonDa, I added it. Thank you!
